FEAT: #7 Create CardView Component
WinterSpringProject/PROJECT-PIND-FE pull request #10
Opened 2021-02-27 03:49 UTC by hysimok

카드에 들어갈 element들을 포함해 카드뷰 컴포넌트를 생성하고 기본적인 배치를 위한 CSS를 적용하였습니다.
padding, margin 등은 디테일은 추후에 보강하겠습니다.

Close #7

2021-02-28 06:19 UTC, gyumnnii requested changes

2021-02-28 06:19 UTC, gyumnnii commented on src/App.js
> +
mock 데이터를 잘 작성해주셨네요!

한 가지 말씀 드리고 싶은 것은
mock 데이터에서 실제 API 데이터로 코드가 교체 돼야 하는 타이밍이 올텐데
컴포넌트 내부 state에 하드코딩을 하게 되면 삭제하거나 변경해야 하는 코드가 많아서
교체 작업이 힘들어 질 수도 있어요!

저는 mock 데이터를 별도 파일로 분리하고 import 해서 사용하는 방법을 추천드립니다!
```js
// mockCard.js
const mockCard={...}
export default mockCard

// App.js
...
import mockCard from '../.../mockCard'

const App=()=>{
  const [cards, setCards]=useState(()=>(mockCard))
  ...
}
```

2021-02-28 06:19 UTC, gyumnnii commented on src/App.js
> +      </CardViewTemplate>
혹시 redux, recoil, context 등의
상태 관리 라이브러리 도입은 예정에 없는지 여쭤보고 싶어요!

2021-02-28 06:19 UTC, gyumnnii commented on src/components/CardView/CardViewListItem.js
> +					<div>서울시 성동구</div>
해당 데이터들도 API로 받아올 것으로 예상이 됩니다.
그렇기에 mock 데이터에 포함해서 작성하시고
데이터를 props로 받아와서 사용하는 코드로 수정하신다면
교체 작업 때에도 해당 컴포넌트는 건들 필요가 없어서 한결 수월할 것 같아 보여요~
(현재 하드코딩 되어 있는 데이터 모두 포함해서 말씀드리는 거예요! (ex. line:12, line:20))

```js
const CardViewListItem=({...})=>{
  ...
  return(
    ...
    <div className="CardViewListItem-projectinfo">
      <div>{props.participantsNumber}</div>
      <div>{props.projectPeriod}</div>
      <div>{props.projectLocation}</div>
    </div>
    ...
  )
}
```

2021-02-28 06:19 UTC, gyumnnii commented on src/components/CardView/CardViewTemplate.js
> +import React from 'react';
CardView에 대한 container 컴포넌트를 따로 정의하신 이유가 있을지 여쭤보고 싶습니다!

2021-02-28 12:37 UTC, hysimok commented on src/components/CardView/CardViewListItem.js
> +					<div>서울시 성동구</div>
mock 데이터에 관한 좋은 아이디어 감사합니다!
이 부분까지 반영해서 mock데이터를 import 할 수 있게 고쳐보겠습니다.

2021-02-28 12:43 UTC, hysimok commented on src/components/CardView/CardViewTemplate.js
> +import React from 'react';
@gyumnnii 
#4 이슈의 이미지에서 카드 형태로 보이는 프로젝트 리스트가 이 카드뷰 컴포넌트인데, 
메인페이지의 다른 컴포넌트들과의 배치를 수월하게 하기 위해 CardViewList를 CardViewTemplate으로 한번 더 감싸서 만들었습니다 ㅎㅎ

2021-02-28 12:45 UTC, hysimok commented on src/App.js
> +      </CardViewTemplate>
예정에 있습니다. 아직 상태 관리 라이브러리의 개념과 사용법이 익숙치 않아서 의논한 건 없지만, 곧 도입하려고 합니다. 😊

2021-02-28 13:54 UTC, Ohhong reviewed
작업 결과에 대한 간단한 사진 정도 캡쳐 해서 보여주시면 좋을 것 같아요~

2021-02-28 13:54 UTC, Ohhong commented on src/components/CardView/CardViewList.js
> +export default CardViewList;
new line 추가해주세요~

2021-02-28 13:54 UTC, Ohhong commented on src/components/CardView/CardViewList.scss
> +}
new line 추가해주세요~

2021-02-28 13:54 UTC, Ohhong commented on src/components/CardView/CardViewListItem.js
> +export default CardViewListItem;
new line 추가해주세요~

2021-02-28 13:54 UTC, Ohhong commented on src/components/CardView/CardViewTemplate.js
> +export default CardViewTemplate;
new line 추가해주세요~

2021-02-28 13:54 UTC, Ohhong commented on src/components/CardView/CardViewTemplate.scss
> +}
new line 추가해주세요~

2021-02-28 15:35 UTC, gyumnnii commented on src/components/CardView/CardViewTemplate.js
> +import React from 'react';
이해했습니다 감사합니다 ^~^

2021-02-28 15:36 UTC, gyumnnii commented on src/App.js
> +      </CardViewTemplate>
상태 관리 라이브러리 도입 등으로 어려우신 점 있으면 편하게 질문해주세요!

2021-03-01 05:36 UTC, hysimok commented
/done

2021-03-01 05:40 UTC, hysimok commented
App.js 에서 충돌이 생겨서 resolve 하긴 했는데 이 PR merge 후 다시 정리해야할 것 같습니다 ㅠㅠ

2021-03-01 08:22 UTC, gyumnnii approved these changes
👍 LGTM 👍

2021-03-02 06:32 UTC, hysimok commented
<img width="1237" alt="스크린샷 2021-03-01 오후 1 09 16" src="https://user-images.githubusercontent.com/13804135/109607919-58b6ee00-7b6c-11eb-8356-44fed53dd8ae.png">
작업결과 캡쳐

2021-03-06 04:46 UTC, merged