Issue/#6 Create NavBar Component
WinterSpringProject/PROJECT-PIND-FE pull request #11
Opened 2021-02-27 11:49 UTC by devbluesea

네비바 메뉴 제작

2021-02-28 06:40 UTC, gyumnnii requested changes

2021-02-28 06:40 UTC, gyumnnii commented on src/App.js
> +import { useState, useCallback } from 'react';
당장 사용하지 않는다면 삭제 하는 것을 추천드릴게요~

이런 코드들이 쌓여서 나중에 번들 사이즈가 예상보다 더 커져버리는 결과를 낳을 수도 있습니다 ㅠ.ㅠ

2021-02-28 06:40 UTC, gyumnnii commented on src/Components/NavBar/CategoryItem.js
> +	const { name, text, click } = CategoryList;
props도 파라미터로 넘겨받는 변수이기 때문에
다른 코드들과 동일하게 lower camelcase 를 지켜서 작성하는 것을 추천 드릴게요!

```suggestion
const CategoryItem = ({categoryList}) => {
	const { name, text, click } = categoryList;
```

2021-02-28 06:40 UTC, gyumnnii commented on src/Components/NavBar/NavBar.js
> +	]);
#10 에서도 언급한 것과 같이
mock data를 API data로 바꿔야 하는 교체시기가 올텐데
그 때 삭제, 변경 돼야 할 코드가 많으면 시간을 많이 소모하게 되면서 정신 건강에 좋지 않습니다.. ㄷㄷ

그래서 저는 해당 mock data를 별도 파일로 빼두고 import해서 사용하는 것을 추천드립니다!
```js
// mockNavigationCategory.js
const mockNavigationCategory={...}
export default mockNavigationCategory

// NavBar.jsx
import mockNavigationCategory from '../.../mockNavigationCategory'
const NavBar=()=>{
  const [navCategory, setNavCategory]=useState(()=>mockNavigationCategory)
}
```

2021-02-28 06:45 UTC, gyumnnii commented
@devbluesea 
추후에 해당 컴포넌트 (네비게이션바, 카테고리바)에 페이지 이동 기능을 추가 해야 할 것 같은데
구현하고자 하는 방식 혹은 사용하고자 하는 라이브러리에 대해 협의가 된 상태인가요?
협의가 되었다면 내용 공유해주시면 좋을 것 같아요!

2021-02-28 06:45 UTC, devbluesea commented on src/Components/NavBar/NavBar.js
> +	]);
@gyumnnii 수정사항 반영해서 다시 올리겠습니다!

2021-02-28 11:40 UTC, devbluesea commented
@gyumnnii 일단은 확정적으로 토의한 것은 없지만 처음에 의견 주고 받을때는 주제별, 지역별은 페이지 이동이 아니라 
<img width="798" alt="Screen Shot 2021-02-28 at 8 36 34 PM" src="https://user-images.githubusercontent.com/23551596/109416987-f42d4f00-7a04-11eb-9e48-fd35cdf26cbf.png">
그림과 같이 네비바 바로 밑 상단에서 보이는 방식을 바꿔줍니다.
그리고 페이지가 변하는 부분은 로그인 부분하고 로고 부분클릭인데
로고부분 클릭은 메인페이지로 가는 것이고 로그인 부분은 로그인 페이지로 라우팅 해줄 것 같습니다.

2021-02-28 15:33 UTC, gyumnnii approved these changes
수정사항 확인했습니다~

수고 많으셨습니다!

2021-03-01 01:33 UTC, hysimok approved these changes

2021-03-01 02:38 UTC, merged