FEAT: #12 Create TopView Component
WinterSpringProject/PROJECT-PIND-FE pull request #18
Opened 2021-03-16 04:39 UTC by devbluesea

Navigation Bar 밑에 상단 카테고리 선택 컴포넌트 구현

2021-03-16 04:55 UTC, devbluesea commented
<img width="1789" alt="Screen Shot 2021-03-16 at 1 54 35 PM" src="https://user-images.githubusercontent.com/23551596/111257863-40140100-865f-11eb-83fa-4b03aa6a812a.png">

변경된 페이지 스크린 샷 입니다.

2021-03-16 10:17 UTC, gyumnnii requested changes
PR에도 자세한 내용이 담겨있으면 좋을 것 같아요
(추가, 변경사항, 데모 이미지 정도..?)

ps.
리뷰어와 링크드 이슈도 등록해주시면 좋을 것 같아요~

2021-03-16 10:17 UTC, gyumnnii commented on src/App.js
> +	);
혜윤님과 포매터 indent 규칙이 다르신 것 같네요.
실제 변경한 것보다 변경되어 보이는 것이 많네요 ㅠㅠ
두 분이서 상의하셔서 통일시키는 것이 좋을 것 같아요~
@hysimok

2021-03-16 10:17 UTC, gyumnnii commented on src/Components/Top/mocTopView.js
> +	},
모든 데이터가 click이 되었는지 여부를 판단하는 flag를 들고있기 보단
현재 클릭된 데이터(클릭된 데이터의 name만..?)를 독립적으로 가지고 있는 것이 더 나아 보이네요

이전에 click 된 data를 찾아서 false로 만든 후에 
현재 click 된 data를 true로 만드는 과정이 소모적일수도 있다는 생각이 들었습니다.

2021-03-16 10:17 UTC, gyumnnii commented on src/Components/Top/TopViewItem.js
> +			<img className = "list-img" src = {imgSample} alt = "img"/>
alt 같은 경우는 이미지 불러오기에 실패하였을 경우
대체 텍스트로 노출되는 친구이기 때문에 좀 더 의미있는 텍스트를 넣는 것을 추천드립니당
```suggestion
			<img className = "list-img" src = {imgSample} alt = `${topViewList.name} image`/>
```

2021-03-16 11:54 UTC, devbluesea commented on src/Components/Top/TopViewItem.js
> +			<img className = "list-img" src = {imgSample} alt = "img"/>
확인했습니다.
1. PR 데모이미지
2. Indent 통일
3. alt 메세지 
고쳐서 다시 올리겠습니다!

2021-03-16 11:57 UTC, devbluesea commented on src/Components/Top/mocTopView.js
> +	},
그 부분은 몰랐는데 클릭 데이터를 하나만 가지고 다시 만들어보겠습니다.

2021-03-18 03:33 UTC, closed without merging

2021-03-18 03:33 UTC, gyumnnii commented on src/Components/Top/TopViewItem.js
> +			<img className = "list-img" src = {imgSample} alt = "img"/>
@devbluesea

2021-03-20 06:31 UTC, devbluesea commented on src/Components/Top/TopViewItem.js
> +			<img className = "list-img" src = {imgSample} alt = "img"/>
@gyumnnii 
indent 문제가 저는 이상 없는데 push하면 계속 똑같아서 다시 만들어봤습니다.