FEAT: use redux to NavBar CategoryList
WinterSpringProject/PROJECT-PIND-FE pull request #23
Opened 2021-03-21 05:51 UTC by hysimok

Navigation Bar의 메뉴에 상태관리 라이브러리를 적용합니다.

+) `주제별` 버튼을 누르면 드롭다운 메뉴가 나오게 하는 것은 하지 않기로 결정했습니다.
추후에  Route 이용해 카테고리 리스트와 프로젝트 카드들을 볼 수 있는 화면으로 넘어가게 하기로 하였습니다.

2021-03-28 03:33 UTC, gyumnnii requested changes

2021-03-28 03:33 UTC, gyumnnii commented on src/components/NavBar/CategoryList.js
> +			onClick={() => selectMenu(name)}
return문 바깥으로 빼서 handling 함수를 따로 추가하는 건 어떨까요?
onClick 이벤트 발생 시 추가돼야 할 구현사항이 늘어나거나 코드 수정이 필요할 때를 생각해보면
함수가 추상화 되어있는 편이 더 좋을 것 같아서 추천드립니다~

2021-03-28 03:33 UTC, gyumnnii commented on src/modules/category.js
> +export default category;
new line 추가해주세요~

2021-03-28 03:33 UTC, gyumnnii commented on src/containers/CategoryContainer.js
> +)(CategoryContainer);
new line 추가 부탁드립니당

2021-03-28 03:33 UTC, gyumnnii commented on src/modules/index.js
> +export default rootReducer;
new line!!!!!!!

2021-03-28 03:33 UTC, gyumnnii commented on src/modules/category.js
> +	menu
보통 구현의 편의를 위해서 액션에서 가지고 있는 데이터를 `payload`로 통일하곤 합니다.
action 마다 넘겨주는 데이터 이름이 다르면 reducer를 작성할 때 해당 데이터 이름이 뭔지 확인해 봐야하는 번거로운 상황이 발생하기도 하더라구요.

ducks 패턴을 도입하셨기 때문에 두 분께서 협의가 된 상태로 사용하신다면 해당 코드도 문제 될 일은 없어 보여서 편한 방식을 선택하시면 될 것 같습니다~

2021-03-29 08:01 UTC, hysimok commented on src/modules/category.js
> +	menu
아 그렇겠네요!! 조언 감사합니다 :D

2021-04-03 16:26 UTC, hysimok commented on src/components/NavBar/CategoryList.js
>  			className={`NavBar-click ${selected === name ? 'selected' : ''}`}>
`onClick={onClickMenu(name)}` 형태로 함수를 고쳤더니 Error: Maximum update depth exceeded 오류가 발생했습니다.
함수호출 -> 랜더링 -> 함수호출 -> 랜더링 이 반복되어 무한루프가 발생하는 오류라고 합니다. ㅠㅠ
selectMenu 함수에는 매개 변수가 필요하기 때문에,
위 코드 처럼 화살표 함수를 중첩하거나, 이전 코드에서 처럼 `onClick={() => selectMenu(name)}` 으로 해결하는 방법이 있었습니다.  함수 분리를 위해 전자의 방법으로 코드를 수정하였습니다.

2021-04-04 02:50 UTC, hysimok commented on src/components/NavBar/CategoryList.js
>  			className={`NavBar-click ${selected === name ? 'selected' : ''}`}>
클로저 알아보기!

2021-04-05 02:32 UTC, hysimok commented on src/components/NavBar/CategoryList.js
>  			{text}
일요일 회의 때 정재님이 조언해주신대로 
클로저, 변수의 스코프에 대해 공부해보고 위와 같이 수정하였습니다

2021-04-05 08:03 UTC, hysimok commented on src/components/NavBar/CategoryList.js
>  			{text}
그런데 공부해보니까,
제가 이해한대로면 클로저는 스코프 수명이 끝난 변수에 접근할 수 있게 하기위해 클로저 함수를 리턴하는 것 같은데,,,,
이 케이스가 클로저에 해당하는게 맞나요 ?? `onClickMenu()` 함수 안은 `name`의 스코프에 해당하지 않는건가요?

2021-04-09 08:56 UTC, merged