프로젝트 상세페이지 구현
WinterSpringProject/PROJECT-PIND-FE pull request #37
Opened 2021-04-17 13:10 UTC by hysimok

1. 상세페이지 컴포넌트 `ProjectDetail` 간단하게 구현 후
    1-1. CSS는 기본 틀만 잡아봤습니다. 추후에 수정하겠습니다.
2. 카드뷰에서 해당 프로젝트 카드를 클릭하면 상세페이지로 이동하게 연결하였습니다.
    2-1. react-route-dom 의 Route, Link 컴포넌트 활용

3. 폴더명 대소문자 차이로 인해 빌드 오류가 발생하는 등, 작은 수정사항들을 고쳤습니다.

![image](https://user-images.githubusercontent.com/13804135/115114332-adea7a00-9fc9-11eb-8212-02cbe511a82b.png)

Close #36

2021-04-18 03:43 UTC, gyumnnii requested changes

2021-04-18 03:43 UTC, gyumnnii commented on src/App.js
> +      <Route path="/" component={CardViewList} exact={true} />
각각의 라우트를 생성하는 것 보다 3가지 컴포넌트를 합쳐서 렌더해주는 컨테이너를 하나 만드는 건 어떨까요?
어짜피 세 컴포넌트 모두 `/` 위치에서는 필수적으로 노출 돼야 하는 컴포넌트들이고 라우트 변경이 아닌 state 변경에 의해 렌더되는 데이터가 바뀌는 친구들인 것 같아서 말씀드립니다!

2021-04-18 03:43 UTC, gyumnnii commented on src/components/CardView/CardViewList.js
> +			<Route path="/project" component={ProjectDetail} />
`CardViewListItem` 내부에서 `/project/:projectId` 로 링크를 연결해 둔 것으로 보이는데 (이 라우트는 `App` 쪽에 정의 돼 있네요!)
해당 라우트는 없애도 괜찮지 않을까요?

2021-04-18 03:43 UTC, gyumnnii commented on src/components/CardView/CardViewListItem.js
> +	const imgUrl = project.file ? `http://52.78.169.232:8080/file?fileName=${project.file.url}`: logo;
서버 도메인(IP)을 한 4개 컴포넌트에서 재사용하는 것으로 보이는데 갈아 끼기 쉽고 한 번에 통제가 가능하게 
별도 파일에서 constant 느낌으로 사용하는 것도 나쁘지 않습니당

```js
// serverInfo.const.js
const SERVER_IP='http://52.78.169.232:8080'

// CardViewListItem.js
const imgUrl=project.file?`${SERVER_IP}/file?fileName=${project.file.url}`:logo;
...

// 

```

2021-04-18 03:43 UTC, gyumnnii commented on src/components/CardView/CardViewListItem.js
> +						<div>{project.region.region3}</div>
아직은 괜찮을 것 같아보이는데 `<div>` 들이 꽤 많이 중첩되는 상황이 온다면 좀 더 작은 단위의 컴포넌트로 나누는 것도 고려해보셔요!

2021-04-18 03:43 UTC, gyumnnii commented on src/components/Project/ProjectDetail.js
> +				console.log(response.data);
`console.log()` 삭제 부탁드릴게욥

2021-04-18 03:43 UTC, gyumnnii commented on src/components/Project/ProjectDetail.js
> +export default ProjectDetail;
new line 추가해주세욥

2021-04-18 03:50 UTC, hysimok commented on src/components/CardView/CardViewList.js
> +			<Route path="/project" component={ProjectDetail} />
!!!매의 눈이시네요. 테스트해보다가 안 뺐나봅니다ㅠㅠ

2021-04-18 04:14 UTC, hysimok commented on src/components/CardView/CardViewListItem.js
> +	const imgUrl = project.file ? `http://52.78.169.232:8080/file?fileName=${project.file.url}`: logo;
오..constant로 만들어두면 나중에 주소 여러개 관리하거나 color 코드같은거 관리하기에도 좋겠네요. 감사합니다!!

2021-04-18 04:26 UTC, hysimok commented on src/components/CardView/CardViewListItem.js
> +						<div>{project.region.region3}</div>
넵! 이 부분은 문제가 더 커지면... 컴포넌트 단위로 나누는 걸 고려해보겠습니다 ㅎㅎ

2021-04-19 04:42 UTC, gyumnnii approved these changes
깔-끔 하네요 👍
고생하셨어요

img 태그 alt 속성 같은 경우는 해당 이미지에 대한 간략한 설명이 들어가면 더 좋겠네요
SEO 같은거 생각하면 꽤나 유용한 정보가 될 수도 있으니까요!

2021-04-19 07:45 UTC, merged