FEAT: #38 Create project
WinterSpringProject/PROJECT-PIND-FE pull request #39
Opened 2021-04-25 05:57 UTC by devbluesea

프로젝트 등록기능 구현 라우팅구현하면서 리펙토링 예정

<img width="363" alt="Screen Shot 2021-04-25 at 2 56 52 PM" src="https://user-images.githubusercontent.com/23551596/115982482-7afe4280-a5d6-11eb-81ee-5f51feadd25e.png">

일단 기능만 구현했고 따로 페이지로 라우팅하는 기능 만들면서 컴포넌트를 더 잘게 나눌 예정입니다.
css는 그 이후에 하겠습니다.

2021-04-26 05:43 UTC, gyumnnii requested changes
프로젝트 클론해서 실행해보면 에러가 나오네요

![스크린샷 2021-04-26 오후 2 41 19](https://user-images.githubusercontent.com/49565544/116034015-78b2eb80-a69d-11eb-8649-0bd7adf836fd.png)

`src/components` 디렉토리를 `src/Components` 로 수정하면서 생긴 에러로 보이네요! (import 시에는 /components 로 하게 구현이 돼 있네요,,,)

2021-04-26 05:43 UTC, gyumnnii commented on src/components/NewProject/InputForm.js
> +		//console.log("address : ", addressList[0].id);
해당 주석 삭제해도 괜찮겠네요~

2021-04-26 05:43 UTC, gyumnnii commented on src/components/NewProject/InputForm.js
> +		//console.log("filtersub : ", subjectList[0].id);
해당 주석도 삭제해도 괜찮을 것 같아요!

2021-04-26 05:43 UTC, gyumnnii commented on src/components/NewProject/InputForm.js
> +	};
`onReset()` 에서 `maxParticipateNum` 필드를 20으로 세팅하시는데
그렇게 되면 제출 클릭 시 최대 참가 인원 input 필드에 20이 노출되네요
의도하신 것이라면 괜찮지만 의도하신 것이 아닌 것 같아 보여서 말씀드려요!

![스크린샷 2021-04-26 오후 2 36 33](https://user-images.githubusercontent.com/49565544/116033784-04784800-a69d-11eb-8a58-73889b4a3d73.png)

2021-04-27 15:48 UTC, devbluesea commented on src/components/NewProject/InputForm.js
> +	};
@gyumnnii 42학교 과제만 끝내고 다시 리팩토링 해서 올리겠습니다~

2021-05-07 12:45 UTC, merged